### ISSUE TITLE
expo SDK issue

### ISSUE THREAD

**Issue by shravanteegala** [thomaswangio/auth-screens#3]
![Simulator Screen Shot - iPhone X - 2019-07-16 at 13 16 14](https://user-images.githubusercontent.com/13646977/61275679-1476ae80-a7cc-11e9-99ea-1a956a1054c0.png)

**Comment by thomaswangio** [comment]
This issue has been resolved thanks to @braytonstafford, I made a few adjustments but everything should be working now without Expo as a dependency. Only need to include `react` and `react-native`!

use `react-native-gradient-buttons v2.0.1` https://www.npmjs.com/package/react-native-gradient-buttons
